### ISSUE TITLE
Choose a release tag convention

### ISSUE THREAD

**Issue by brylie** [SpaceTalk/SpaceTalk#123]
SpaceTalk project releases are currently following the semantic version scheme. However, our current release tags (e.g. `release/SPACETALK@0.1.1`) add extra and redundant metadata.  This leads to inelegant URIs like the following:

`https://github.com/SpaceTalk/SpaceTalk/releases/tag/release%2FSPACETALK%400.1.1`

Consider how to simplify the release tags, for:
- clarity
- simplicity
- consistency
## Task
- [ ] Consider possible release tag conventions
  - [ ] Full release
  - [ ] pre-release alpha
  - [ ] pre-release beta
- [ ] Choose a convention for each type of release
- [ ] Document the chosen conventions for project developers to understand
- [ ] Update the 0.1.0 and 0.1.1 tags to follow the chosen convention, if necessary

**Comment by brylie** [comment]
I propose we simply tag releases with the version number (e.g. `0.1.2`), at the most, perhaps adding a 'v' prefix. To this end, I have set up a [draft release for consideration](https://github.com/SpaceTalk/SpaceTalk/releases/tag/untagged-71254e8540fffae2f1c0).

**Comment by brylie** [comment]
Additionally, pre-releases need some convention (e.g. `v0.1.2-a1`, `v0.1.2-b2`, etc.).
